spring:
  application:
    name: petstore-springboot
  http:
    clients:
      connect-timeout: 2s
      read-timeout: 10s

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true

endpoints:
  order:
    host: http://localhost:9000
  pet:
    host: http://localhost:9000
